// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aicfrlxqskcuswmxvolj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpY2ZybHhxc2tjdXN3bXh2b2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODExOTIsImV4cCI6MjA2OTQ1NzE5Mn0.cVk-qHqWHN-_Il41sG0tKgZAZvi2TQ9WYD-Nt-lUk8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});